name: sync-news-test
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      WP_URL : ${{ secrets.WP_URL }}
      WP_USER: ${{ secrets.WP_USER }}
      WP_PASS: ${{ secrets.WP_PASS }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt

      - name: Fetch JP posts
        run: python scripts/fetch_rss.py      # ← ここで queue を生成

      - name: Translate & publish 10 langs
        run: python scripts/translate_post.py
