# --------------------------------------------
# .github/workflows/sync_multi.yml (12h, multi-lang)
# --------------------------------------------
name: Sync JP→MultiLang

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        lang: [en, es, pt, id, zhhans, zhhant]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Run sync for ${{ matrix.lang }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WP_URL:  ${{ secrets[ format('WP_URL_{0}',  matrix.lang) ] }}
          WP_USER: ${{ secrets[ format('WP_USER_{0}', matrix.lang) ] }}
          WP_PASS: ${{ secrets[ format('WP_PASS_{0}', matrix.lang) ] }}
          TARGET_LANG: ${{ matrix.lang }}
        run: |
          python scripts/fetch_posts.py
          python scripts/translate_post.py --lang $TARGET_LANG
