name: i18n-sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"   # 4 時間ごと

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      WP_URL : ${{ secrets.WP_URL }}
      WP_USER: ${{ secrets.WP_USER }}
      WP_PASS: ${{ secrets.WP_PASS }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run pipeline
        run: |
          python scripts/fetch_rss.py
          python scripts/translate_post.py
          python scripts/post_to_wp.py
